Chapter 1 Update
xieliaing/CausalInferenceIntro pull request #3
Opened 2022-04-06 01:00 UTC by kangqiao-ctrl

- Polished the latter half of Chapter 1. 
- Revised some of the expressions in the first half of the chapter.
- Standardized some usages, e.g., "处理", "个体", etc.

2022-04-08 11:34 UTC, xieliaing commented on chapters/01 第一章-因果关系入门.ipynb
> +    "2. 处理因素本身之外，处理组和和未处理组之间的其他差异。在这种情况下，处理组和未处理组的区别在于处理组的学费要高得多，导致了考试成绩的一部分差异。因为更高的学费意味着更好的教育。\n",
这个翻译值得商榷。原文在讲差异事实的时候只提及了学费，同一句里面无分句讲导致的结果，但是你的翻译似乎强调就是因为学费的差异导致的成绩的差异。但是，原文在强调原因的时候也只是说“some of the difference.... can be due to ”，是一种较为保守的说法。

2022-04-08 11:37 UTC, xieliaing approved these changes

2022-04-08 11:38 UTC, xieliaing approved these changes

2022-04-08 11:42 UTC, xieliaing approved these changes

2022-04-08 13:59 UTC, kangqiao-ctrl commented on chapters/01 第一章-因果关系入门.ipynb
> +    "2. 处理因素本身之外，处理组和和未处理组之间的其他差异。在这种情况下，处理组和未处理组的区别在于处理组的学费要高得多，导致了考试成绩的一部分差异。因为更高的学费意味着更好的教育。\n",
有道理。现在改为了“考试成绩的一部分差异可能是由于更高的学费意味着更好的教育。”

2022-04-12 00:57 UTC, xieliaing commented on chapters/01 第一章-因果关系入门.ipynb
> +    "2. 处理因素本身之外，处理组和和未处理组之间的其他差异。在这种情况下，处理组和未处理组的区别在于处理组的学费要高得多，导致了考试成绩的一部分差异。因为更高的学费意味着更好的教育。\n",
Thanks.

2022-04-12 00:59 UTC, xieliaing approved these changes

2022-04-13 06:14 UTC, xieliaing approved these changes

2022-04-13 06:15 UTC, xieliaing requested changes

2022-04-13 06:15 UTC, xieliaing commented on chapters/01 第一章-因果关系入门.ipynb
> +    "首先，也是最关键的一点，你可能会想：因果关系我来说，有什么用？那我们就围绕这一点展开说说。\n",
“因果关系我来说”----》“因果关系对我来说”

2022-04-13 06:16 UTC, xieliaing commented on chapters/01 第一章-因果关系入门.ipynb
> +    "## 为什么要关心因果关系？\n",
这种minor的修改不是很有必要。

2022-04-13 06:26 UTC, xieliaing requested changes

2022-04-13 06:26 UTC, xieliaing commented on chapters/01 第一章-因果关系入门.ipynb
> +    "然而，ML 并不是万能的。它的确可以在非常严格的边界下创造奇迹，但如果新的数据与模型习惯的数据略有不同，它仍然会败得很惨。再举一个来自 《预测机器》 的例子，“在许多行业中，低价格是与低销量相关的。比如在酒店行业，旅游旺季以外的客房价格低，而需求旺盛、酒店爆满时客房价格反而高。基于这样的数据训练的一个简单预测模型（naive prediction）可能会直接给出结论：提高客房售价会导致
建议以如下方式保留英文书名：《预测机器》（Prediction Machine）

2022-04-13 06:26 UTC, xieliaing commented on chapters/01 第一章-因果关系入门.ipynb
> +    "也就是说，对于接受了处理的学校，平均来看，平板电脑使学生的学习成绩降低了 75 分。当然，没有神力加持的话，现实中我们根本没办法知道这些数据。上面的表格在现实世界中看起来将是下面这样："
后半句没有修改的必要

2022-04-13 06:26 UTC, xieliaing commented on chapters/01 第一章-因果关系入门.ipynb
> +    "与此同时，那些一直在基于数据做“老式”科学的人则有点被我们忘在脑后了。这么多年来，经济学家们都在试图回答：教育对一个人收入的真正影响是什么；生物统计学家们为了弄清楚饱和脂肪是否会导致更高的心脏病发病率而绞尽脑汁；而心理学家则希望了解[肯定言语](https://en.wikipedia.org/wiki/The_Five_Love_Languages)是否真的能让婚姻更幸福。老实说，“
这里似乎没有diff？

2022-04-13 06:27 UTC, xieliaing commented
建议一次PR不要涉及太多修订

2022-04-13 06:44 UTC, kangqiao-ctrl commented on chapters/01 第一章-因果关系入门.ipynb
> +    "也就是说，对于接受了处理的学校，平均来看，平板电脑使学生的学习成绩降低了 75 分。当然，没有神力加持的话，现实中我们根本没办法知道这些数据。上面的表格在现实世界中看起来将是下面这样："
这里是基于我之前某次commit的一个小的语序改动。也是这次提交Commit过多，review起来会有点累。我会把这个PR取消，resolve所有的comments之后合并一下我所有的commit，再重新提交。

2022-04-13 06:44 UTC, kangqiao-ctrl commented on chapters/01 第一章-因果关系入门.ipynb
> +    "## 为什么要关心因果关系？\n",
好的。想着说作为标题，能减少一个字就减少一个字。会在下一次提交时回滚。

2022-04-13 06:45 UTC, kangqiao-ctrl commented on chapters/01 第一章-因果关系入门.ipynb
> +    "与此同时，那些一直在基于数据做“老式”科学的人则有点被我们忘在脑后了。这么多年来，经济学家们都在试图回答：教育对一个人收入的真正影响是什么；生物统计学家们为了弄清楚饱和脂肪是否会导致更高的心脏病发病率而绞尽脑汁；而心理学家则希望了解[肯定言语](https://en.wikipedia.org/wiki/The_Five_Love_Languages)是否真的能让婚姻更幸福。老实说，“
数据科学加了一个引号，想籍引号强调"数据科学"这一概念nothing new的本质。

2022-04-13 06:45 UTC, kangqiao-ctrl commented on chapters/01 第一章-因果关系入门.ipynb
> +    "然而，ML 并不是万能的。它的确可以在非常严格的边界下创造奇迹，但如果新的数据与模型习惯的数据略有不同，它仍然会败得很惨。再举一个来自 《预测机器》 的例子，“在许多行业中，低价格是与低销量相关的。比如在酒店行业，旅游旺季以外的客房价格低，而需求旺盛、酒店爆满时客房价格反而高。基于这样的数据训练的一个简单预测模型（naive prediction）可能会直接给出结论：提高客房售价会导致
好的。会在下一次提交时修改。

2022-04-13 06:46 UTC, kangqiao-ctrl commented
> 建议一次PR不要涉及太多修订

好的，没有问题。今后也会在合并Commit之后再提交。

2022-04-13 06:46 UTC, closed without merging

2022-04-13 06:49 UTC, kangqiao-ctrl commented on chapters/01 第一章-因果关系入门.ipynb
> +    "首先，也是最关键的一点，你可能会想：因果关系我来说，有什么用？那我们就围绕这一点展开说说。\n",
这是一个Outdated Commit，在最新的版本中是已修正的。我会把Commit整理一下重新提交。